"""removed unique code

Revision ID: 34527f972930
Revises: 027e74867eab
Create Date: 2024-10-12 08:54:27.299248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34527f972930'
down_revision: Union[str, None] = '027e74867eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_codes_code_key', 'user_codes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_codes_code_key', 'user_codes', ['code'])
    # ### end Alembic commands ###
