"""made unique user_id in user_code

Revision ID: 859e2dad66ce
Revises: 34527f972930
Create Date: 2024-10-12 09:01:42.358987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859e2dad66ce'
down_revision: Union[str, None] = '34527f972930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_codes', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_codes', type_='unique')
    # ### end Alembic commands ###
